#!/bin/bash  # Simple CPU load generator script for stress testing
set -euo pipefail # safer bash scripting

echo "Generating CPU load (Ctrl+C to stop)" # Inform user   
while :; do # Infinite loop to generate load
  openssl rand -base64 1000000 | sha256sum > /dev/null # Generate load
done # End of loop
